//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuegoCienMexicanos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int idAnswer { get; set; }
        public string answer { get; set; }
        public int score { get; set; }
        public int place { get; set; }
    
        public virtual Question_Answer Question_Answer { get; set; }
    }
}
